# Generated by Django 5.0.4 on 2024-04-10 12:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Author Name')),
                ('image', models.ImageField(blank=True, null=True, upload_to='authors/', verbose_name='Image')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Description')),
            ],
            options={
                'verbose_name': 'Author',
                'verbose_name_plural': 'Authors',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Books',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book_name', models.CharField(max_length=100, verbose_name='Book Name')),
                ('page_count', models.IntegerField(null=True, verbose_name='Page Count')),
                ('category', models.CharField(max_length=100, verbose_name='Category')),
                ('price', models.DecimalField(decimal_places=2, max_digits=6, verbose_name='Price')),
                ('image', models.ImageField(blank=True, null=True, upload_to='images/', verbose_name='Image')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='books', to='books_store.author')),
            ],
            options={
                'verbose_name': 'Book',
                'verbose_name_plural': 'Books',
                'ordering': ['book_name', 'price', 'page_count'],
                'indexes': [models.Index(fields=['book_name'], name='name_idx'), models.Index(fields=['price'], name='price_idx'), models.Index(fields=['page_count'], name='page_count_idx')],
            },
        ),
        migrations.AddConstraint(
            model_name='books',
            constraint=models.UniqueConstraint(fields=('book_name', 'author'), name='unique_book'),
        ),
    ]
