# Generated by Django 5.0.4 on 2024-04-10 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books_store', '0002_remove_books_page_count_idx_author_wiki_page'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='books',
            options={'ordering': ['name', 'price', 'page_count'], 'verbose_name': 'Book', 'verbose_name_plural': 'Books'},
        ),
        migrations.RemoveConstraint(
            model_name='books',
            name='unique_book',
        ),
        migrations.RemoveIndex(
            model_name='books',
            name='name_idx',
        ),
        migrations.RenameField(
            model_name='books',
            old_name='book_name',
            new_name='name',
        ),
        migrations.AddIndex(
            model_name='books',
            index=models.Index(fields=['name'], name='name_idx'),
        ),
        migrations.AddConstraint(
            model_name='books',
            constraint=models.UniqueConstraint(fields=('name', 'author'), name='unique_book'),
        ),
    ]
