# Generated by Django 5.0.4 on 2024-04-14 14:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books_store', '0004_category_remove_books_category_books_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='books',
            name='cover_type',
            field=models.CharField(choices=[('Softcover', 'Softcover'), ('Hardcover', 'Hardcover'), ('E-book', 'E-book')], default='soft', max_length=10, verbose_name='Cover Type'),
        ),
        migrations.AlterField(
            model_name='books',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='books', to='books_store.author', verbose_name='Author'),
        ),
    ]
